# Permalinks
permalink:           pretty

# Setup
title:               rlanyi
tagline:             today i learned
description:         I'm rlanyi, also known as Alki and this is my repo of handy stuff that I learned today. And yesterday.
url:                 https://rlanyi.github.io/
paginate:            2
baseurl:             ""
comments:            true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Robert Lanyi
  url:               https://rlanyi.github.io/
  email:             lanyi.robert.attila@gmail.com

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
